"""init

Revision ID: a47adacf2a2e
Revises: 
Create Date: 2026-02-10 20:14:05.283531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47adacf2a2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('old', sa.Enum('25', '26', '27', '28', '29', '30', '31', '32'), nullable=True),
    sa.Column('jenre', sa.Enum('HIPHOP', 'BREAK', 'LOCK', 'POP', 'JAZZ', 'WAACK', 'HOUSE'), nullable=True),
    sa.Column('section', sa.Enum('1', '2', '3'), nullable=True),
    sa.Column('rehersal', sa.Enum('1', '2'), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checked_passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('old', sa.Enum('25', '26', '27', '28', '29', '30', '31', '32'), nullable=True),
    sa.Column('section', sa.Enum('1', '2', '3'), nullable=True),
    sa.Column('rehersal', sa.Enum('1', '2'), nullable=True),
    sa.Column('jenre', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('old', sa.Enum('25', '26', '27', '28', '29', '30', '31', '32'), nullable=True),
    sa.Column('jenre', sa.String(length=1000), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history_name', sa.String(length=1000), nullable=True),
    sa.Column('driver_name', sa.String(length=1000), nullable=True),
    sa.Column('passenger_name', sa.String(length=1000), nullable=True),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_name', sa.String(length=1000), nullable=True),
    sa.Column('passenger_name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.Column('old', sa.Enum('25', '26', '27', '28', '29', '30', '31', '32'), nullable=True),
    sa.Column('jenre', sa.Enum('HIPHOP', 'BREAK', 'LOCK', 'POP', 'JAZZ', 'WAACK', 'HOUSE'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('passengers')
    op.drop_table('log_history')
    op.drop_table('history')
    op.drop_table('drivers')
    op.drop_table('checked_passengers')
    op.drop_table('checked_drivers')
    # ### end Alembic commands ###
