"""add mode column to log_history

Revision ID: fa0c5a4b2645
Revises: a47adacf2a2e
Create Date: 2026-02-11 14:44:43.693339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa0c5a4b2645'
down_revision = 'a47adacf2a2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_history', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
